### ISSUE TITLE
No problem but a feature request instead of highlighting every square

### ISSUE THREAD

**Issue by ShrrgWolf** [Krazune/LineOfSight#1]
Instead of highlighting every square within line of sight, could there be an option to toggle and just show an outline of max range and where things block view. In img attached what im proposing is just showing the red line and removing all the other tile markers
ive been waiting for a plugin like this thank you!

![image](https://user-images.githubusercontent.com/38446510/145135718-3a12a420-7f98-425f-bc44-479f8ac86610.png)

**Comment by Krazune** [comment]
I like this suggestion, I'll see what I can do.

**Comment by Krazune** [comment]
This new feature is almost done:
![los](https://user-images.githubusercontent.com/10135839/145681872-6519c8f4-7cfb-4786-8ff2-7cefd0bb3b0f.png)
I'll change a few other things and I will add it to the next update.

**Comment by ShrrgWolf** [comment]
looks great! thank you!

**Comment by Krazune** [comment]
I released the new version, and sent the changes to runelite.
Once it gets added to runelite, [here](https://github.com/runelite/plugin-hub/pull/2171), I will close this issue.

**Comment by Krazune** [comment]
It has been added to runelite.
